//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aSIMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageNaming {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageNaming() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aSIMS.MessageNaming", typeof(MessageNaming).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Request cannot be Executed Successfully.
        /// </summary>
        public static string ErrorDataDelete {
            get {
                return ResourceManager.GetString("ErrorDataDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Requested Data is Successfully Deleted.
        /// </summary>
        public static string SuccessDataDelete {
            get {
                return ResourceManager.GetString("SuccessDataDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Entered is Successfully Saved.
        /// </summary>
        public static string SuccessDataEntry {
            get {
                return ResourceManager.GetString("SuccessDataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Updation is Successfully Saved.
        /// </summary>
        public static string SuccessDataUpdate {
            get {
                return ResourceManager.GetString("SuccessDataUpdate", resourceCulture);
            }
        }
    }
}
