CREATE DATABASE aSIMS
GO
USE aSIMS

CREATE TABLE AccountRole(
	RoleID INT IDENTITY(1,1) NOT NULL,
	RoleName NVARCHAR(50) NOT NULL,
	Description NVARCHAR(200) NULL,
	UserTypeID INT NOT NULL,
	CONSTRAINT PK_AccountRole PRIMARY KEY CLUSTERED (RoleID)
	CONSTRAINT FK_AccountRole_UserTypeID FOREIGN KEY (UserTypeID) REFERENCES UserType(UserTypeID)
)
GO

CREATE TABLE Gender(
	GenderID INT IDENTITY(1,1) NOT NULL,
	GenderName NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_Gender PRIMARY KEY CLUSTERED (GenderID)
)
GO
CREATE TABLE City(
	CityID INT IDENTITY(1,1) NOT NULL,
	CityName NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_City PRIMARY KEY CLUSTERED (CityID)
)
GO
CREATE TABLE Designation(
	DesignationID INT IDENTITY(1,1) NOT NULL,
	DesignationName NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_Designation PRIMARY KEY CLUSTERED (DesignationID)
)
GO
CREATE TABLE UserType(
	UserTypeID INT IDENTITY(1,1) NOT NULL,
	UserTypeName NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_UserType PRIMARY KEY CLUSTERED (UserTypeID)
)
GO
CREATE TABLE GroupSection(
	GroupSectionID INT IDENTITY(1,1) NOT NULL,
	GroupSectionName NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_GroupSection PRIMARY KEY CLUSTERED (GroupSectionID)
)
GO

CREATE TABLE EmployeeAccount(
	UserID INT IDENTITY(1,1) NOT NULL,
	UserCode VARCHAR(8) NOT NULL,
	UserName VARCHAR(25) NULL,
	Password NVARCHAR(200) NULL,
	FullName NVARCHAR(50) NOT NULL,
	EmailAddress VARCHAR(100) NOT NULL,
	Phone VARCHAR(20) NULL,
	Mobile VARCHAR(20) NULL,
	Address NVARCHAR(100) NOT NULL,
	DateOfBirth DATE NOT NULL,
	CNIC VARCHAR(20) NULL,
	RoleID INT NOT NULL,
	GenderID INT NOT NULL,
	CityID INT NOT NULL,
	DesignationID INT NOT NULL,
	UserTypeID INT NOT NULL,
	IsDeleted BIT NOT NULL,
	EntryUser INT NOT NULL,
	EntryDate DATE NOT NULL,
	UpdateUser INT NULL,
	UpdateDate DATE NULL,
	CONSTRAINT PK_UserAccount PRIMARY KEY CLUSTERED (UserID),
	CONSTRAINT UK_UserAccount UNIQUE (UserName),
	CONSTRAINT FK_UserAccount_AccountRole FOREIGN KEY (RoleID) REFERENCES AccountRole(RoleID),
	CONSTRAINT FK_UserAccount_GenderID FOREIGN KEY (GenderID) REFERENCES Gender(GenderID),
	CONSTRAINT FK_UserAccount_CityID FOREIGN KEY (CityID) REFERENCES City(CityID),
	CONSTRAINT FK_UserAccount_DesignationID FOREIGN KEY (DesignationID) REFERENCES Designation(DesignationID),
	CONSTRAINT FK_UserAccount_UserTypeID FOREIGN KEY (UserTypeID) REFERENCES UserType(UserTypeID)
)
GO

CREATE TABLE Transport (
	TransportID INT IDENTITY(1,1) NOT NULL,
	TransportName VARCHAR(50) NOT NULL,
	RouteArea VARCHAR(100) NULL,
	NumberOfVehicle INT NOT NULL,
	VehicleNumber VARCHAR(20) NOT NULL,
	DriverCNIC VARCHAR(20) NOT NULL,
	DriverMobile VARCHAR(20) NOT NULL,
	RouteFare FLOAT NULL,
	Description VARCHAR(200) NULL,
	EntryUser INT NOT NULL,
	EntryDate DATE NOT NULL,
	UpdateUser INT NULL,
	UpdateDate DATE NULL,
	IsDeleted BIT NOT NULL,
	CONSTRAINT PK_Transport PRIMARY KEY CLUSTERED (TransportID)
)
GO

CREATE TABLE Navbar(
	MenuID INT NOT NULL,
	LinkText VARCHAR(50) NOT NULL,
	ActionName VARCHAR(50) NULL,
	ControllerName VARCHAR(50) NULL,
	Icon VARCHAR(50) NULL,	
	ParentID INT NULL,
	ShowInMenu INT,
	IsParent INT,
	SequenceNumber INT,
	CONSTRAINT PK_Menu PRIMARY KEY CLUSTERED (MenuID),
	CONSTRAINT FK_Menu_Menu FOREIGN KEY(ParentID)REFERENCES Navbar(MenuID)
)
GO

CREATE TABLE RoleAccessRights(
	RoleID INT NOT NULL,
	MenuID INT NOT NULL,
	CONSTRAINT FK_RoleAccessRights_AccountRole FOREIGN KEY(RoleID) REFERENCES AccountRole (RoleID),
	CONSTRAINT FK_RoleAccessRights_Menu FOREIGN KEY(MenuID) REFERENCES Navbar (MenuID)
)
GO

CREATE TABLE Teachers(
	TeacherID INT IDENTITY(1,1) NOT NULL,
	TeacherName VARCHAR(50) NOT NULL,
	DateOfBirth DATE NULL,
	GenderID INT NOT NULL,
	Address NVARCHAR(100) NOT NULL,
	Phone VARCHAR(20) NULL,
	Mobile VARCHAR(20) NULL,
	Email VARCHAR(50) NULL,
	UserName VARCHAR(25) NOT NULL,
	Password VARCHAR(25) NOT NULL,
	Qualification VARCHAR(50) NOT NULL,
	GroupSectionID INT NOT NULL,
	CNIC VARCHAR(20) NULL,
	CityID INT NOT NULL,
	RoleID INT NOT NULL,
	DesignationID INT NOT NULL,
	UserTypeID INT NOT NULL,
	IsDeleted BIT NOT NULL,
	EntryUser INT NOT NULL,
	EntryDate DATE NOT NULL,
	UpdateUser INT NULL,
	UpdateDate DATE NULL,
	CONSTRAINT PK_Teacher PRIMARY KEY CLUSTERED (TeacherID),
	CONSTRAINT FK_Teacher_GenderID FOREIGN KEY(GenderID) REFERENCES Gender(GenderID),
	CONSTRAINT FK_Teacher_UserTypeID FOREIGN KEY(UserTypeID) REFERENCES UserType(UserTypeID),
	CONSTRAINT FK_Teacher_CityID FOREIGN KEY(CityID) REFERENCES City(CityID),
	CONSTRAINT FK_Teacher_GroupSectionID FOREIGN KEY(GroupSectionID) REFERENCES GroupSection(GroupSectionID)
)
GO

CREATE TABLE Parents(
	ParentID INT IDENTITY(1,1) NOT NULL,
	ParentName VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NULL,
	Password VARCHAR(25) NULL,
	Phone VARCHAR(20) NULL,
	Mobile VARCHAR(20) NOT NULL,	
	Address VARCHAR(100) NOT NULL,
	Profession VARCHAR(50) NOT NULL,
	EntryUser INT NOT NULL,
	EntryDate DATE NOT NULL,
	UpdateUser INT NULL,
	UpdateDate DATE NULL,
	IsDeleted BIT NOT NULL,
	CONSTRAINT PK_Parents PRIMARY KEY CLUSTERED (ParentID)
)
GO

CREATE TABLE Classes(
	ClassID INT IDENTITY(1,1) NOT NULL,
	ClassName VARCHAR(30) NOT NULL,
	ClassNumericName VARCHAR(5) NOT NULL,
	CONSTRAINT PK_Classes PRIMARY KEY CLUSTERED (ClassID)
)
GO

CREATE TABLE Sections(
	SectionID INT IDENTITY(1,1) NOT NULL,
	SectionName VARCHAR(5) NOT NULL,
	ClassID INT NOT NULL,
	TeacherID INT,
	CONSTRAINT PK_Sections PRIMARY KEY CLUSTERED (SectionID),
	CONSTRAINT FK_Sections_TeacherID FOREIGN KEY(TeacherID) REFERENCES Teachers(TeacherID),
	CONSTRAINT FK_Sections_ClassID FOREIGN KEY(ClassID) REFERENCES Classes(ClassID)
)
GO

CREATE TABLE Students (
	StudentID INT IDENTITY(1,1) NOT NULL,
	EnrollmentNumber VARCHAR(50) NOT NULL,
	StudentName VARCHAR(5) NOT NULL,
	RollNumber VARCHAR(10) NOT NULL,
	ParentID INT NOT NULL,
	SectionID INT NOT NULL,
	DateOfBirth DATE NOT NULL,
	GenderID INT NOT NULL,
	Address VARCHAR(200) NULL,
	Phone VARCHAR(50) NULL,
	Email VARCHAR(50) NULL,
	TransportID INT NOT NULL,
	Photo NVARCHAR(MAX) NULL,
	EntryUser INT NOT NULL,
	EntryDate DATE NOT NULL,
	UpdateUser INT NULL,
	UpdateDate DATE NULL,
	IsDeleted BIT NOT NULL,
	IsPassOut BIT NOT NULL,
	ISDropOut BIT NOT NULL,
	CONSTRAINT PK_Students PRIMARY KEY CLUSTERED (StudentID),
	CONSTRAINT FK_Students_SectionID FOREIGN KEY(SectionID) REFERENCES Sections(SectionID),
	CONSTRAINT FK_Students_GenderID FOREIGN KEY(GenderID) REFERENCES Gender(GenderID),
	CONSTRAINT FK_Students_TransportID FOREIGN KEY(TransportID) REFERENCES Transport(TransportID),
	CONSTRAINT FK_Students_ParentID FOREIGN KEY(ParentID) REFERENCES Parents(ParentID)
)
GO